// <auto-generated />
using Holiday.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Holiday.Migrations
{
    [DbContext(typeof(HolidayContext))]
    [Migration("20200625103947_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Holiday.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("int");

                    b.Property<string>("VacantionId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("VacantionId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Holiday.Models.Vacantion", b =>
                {
                    b.Property<string>("VacantionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VacantionDays")
                        .HasColumnType("int");

                    b.Property<string>("VacantionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VacantionId");

                    b.ToTable("Vacantions");
                });

            modelBuilder.Entity("Holiday.Models.Employee", b =>
                {
                    b.HasOne("Holiday.Models.Vacantion", "Vacantion")
                        .WithMany()
                        .HasForeignKey("VacantionId");
                });
#pragma warning restore 612, 618
        }
    }
}
